name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0点自动执行
  workflow_dispatch:     # 支持手动触发

jobs:
  sync-and-modify:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Checkout Fork
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Add Upstream Remote
      run: |
        git remote add upstream https://github.com/Blueforcer/awtrix3.git
        git fetch upstream

    - name: Merge Upstream Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git merge upstream/main --allow-unrelated-histories -m "Merge upstream changes"

    - name: Modify DisplayManager.cpp
      run: |
        sed -i '/case 2:/,/break;/ {
          /break;/a\
            case 3:\\
              matrix = new FastLED_NeoMatrix(leds, 32, 8, NEO_MATRIX_TOP + NEO_MATRIX_LEFT + NEO_MATRIX_COLUMNS + NEO_MATRIX_PROGRESSIVE);\\
              break;\\
            case 4:\\
              matrix = new FastLED_NeoMatrix(leds, 32, 8, NEO_MATRIX_TOP + NEO_MATRIX_LEFT + NEO_MATRIX_ROWS + NEO_MATRIX_PROGRESSIVE);\\
              break;
        }' src/DisplayManager.cpp

    - name: Commit Changes
      if: success()
      run: |
        git add src/DisplayManager.cpp
        git diff --quiet && git diff --staged --quiet || git commit -m "Add new matrix configurations"
        git push origin main
